### PR TITLE
🛠️ Adapt to actions/upload-artifact action to v4

### LINKED ISSUE #316: upload-artefact@v4 is incompatible with our advertised way of handling multiple python versions
https://github.com/actions/upload-artifact#breaking-changes
> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.

We used to upload all coverage files to the same artifact, and they were automatically merged. This is not possible anymore.

### PR DESCRIPTION
**Pull request by keunhyung-chung**
## ⭐ What does this PR do?

- Fixes #316

## 🚀 What I've done

- [x] Update the README with the instructions

### CODE REVIEW

**Review by ewjoachim — APPROVED** [review]

**Review by ewjoachim — APPROVED** [review]
/e2e

**Review by ewjoachim — APPROVED** [review]
/e2e

**Review by ewjoachim — APPROVED** [review]
/e2e
(it's going to work in the end :crossed_fingers: )

**Review by ewjoachim — APPROVED** [review]
/e2e

/whistle :kissing: :musical_note:
Everything's fine !

**Comment by ewjoachim** [comment]
That's quite messed up. I trigger a workflow when I review this PR. I can't run the e2e tests in that workflow. When that workflow ends, it triggers a second workflow. The second workflow is able to run the e2e tests, but it needs to know the PR number.
The 2nd workflow has access to the `workflow_run` event describing the 1st workflow and to the whole github API. Yet, for the life of me, I can't link the 1st workflow to this PR.

Because this PR and #314 share the same branch name, it seems GitHub is convinced that the workflow belongs to PR 314...

**Comment by keunhyung-chung** [comment]
> That's quite messed up. I trigger a workflow when I review this PR. I can't run the e2e tests in that workflow (for permission reasons. This workflow is linked to your fork and has limited rights. So far so good.). When that workflow ends, it triggers a second workflow. The second workflow is able to run the e2e tests, but it needs to know the PR number. The 2nd workflow has access to the `workflow_run` event describing the 1st workflow and to the whole github API. Yet, for the life of me, I can't link the 1st workflow to this PR.
> 
> Because this PR and #314 share the same branch name, it seems GitHub is convinced that the workflow belongs to PR 314...

@ewjoachim Thanks for the detailed explanation 👍. Is there any thing to do from my side?

**Review by ewjoachim — APPROVED** [review]
Don't mind me.

**Comment by ewjoachim** [comment]
> @ewjoachim Thanks for the detailed explanation 👍. Is there any thing to do from my side?

Haha, sorry. I'll just take your commits, put them in a differently-named branch, create a new PR and it "should" work.

Sorry for all the noise 😅

**Comment by ewjoachim** [comment]
Closed by #326

**Comment by ewjoachim** [comment]
Released: https://github.com/py-cov-action/python-coverage-comment-action/releases/tag/v3.16

**Pull request closed without merging**
