### PR TITLE
This is a test PR

### PR DESCRIPTION
**Pull request by ewjoachim**
This PR introduces bogus code, but is here as a draft for collaborating on improving the coverage comment, related to #189

### CODE REVIEW

**Comment by ewjoachim** [comment]
Coverage<br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>functions/example_completed</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_completed/example_completed.py">example_completed.py</a></td><td>64</td><td>19</td><td>70%</td><td><a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_completed/example_completed.py#L33">33</a>, <a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_completed/example_completed.py#L39-L45">39&ndash;45</a>, <a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_completed/example_completed.py#L48-L51">48&ndash;51</a>, <a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_completed/example_completed.py#L55-L58">55&ndash;58</a>, <a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_completed/example_completed.py#L65-L70">65&ndash;70</a>, <a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_completed/example_completed.py#L91-L92">91&ndash;92</a></td></tr><tr><td colspan="5"><b>functions/example_manager</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_manager/example_manager.py">example_manager.py</a></td><td>44</td><td>11</td><td>75%</td><td><a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_manager/example_manager.py#L31-L33">31&ndash;33</a>, <a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_manager/example_manager.py#L49-L55">49&ndash;55</a>, <a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_manager/example_manager.py#L67-L69">67&ndash;69</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_manager/example_static.py">example_static.py</a></td><td>40</td><td>2</td><td>95%</td><td><a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_manager/example_static.py#L60-L61">60&ndash;61</a></td></tr><tr><td colspan="5"><b>functions/my_exampels</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/my_exampels/example.py">example.py</a></td><td>20</td><td>20</td><td>0%</td><td><a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/my_exampels/example.py#L1-L31">1&ndash;31</a></td></tr><tr><td colspan="5"><b>functions/resources</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/resources/resources.py">resources.py</a></td><td>26</td><td>26</td><td>0%</td><td><a href="https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/resources/resources.py#L1-L37">1&ndash;37</a></td></tr><tr><td><b>TOTAL</b></td><td><b>1055</b></td><td><b>739</b></td><td><b>30%</b></td><td>&nbsp;</td></tr></tbody></table></details>

| Tests | Skipped | Failures | Errors   | Time               |
| ----- | ------- | -------- | -------- | ------------------ |
| 109   | 2 :zzz: | 1 :x:    | 0 :fire: | 0.583s :stopwatch: |

**Comment by ewjoachim** [comment]
<add>bar</add>
<del>foo</del>

**Comment by ewjoachim** [comment]
I don't have any other idea for my comment above. I believe we're good from my point of view. Any other change you'd like to make @kieferro ?

**Comment by kieferro** [comment]
> I don't have any other idea for my comment above. I believe we're good from my point of view. Any other change you'd like to make @kieferro ?


That looks pretty good. Much clearer and more informative. However, I still have two things:
* Is `coverage_comment/` in this case supposed to be understood as `COVERAGE_PATH` or do we want to combine files in one folder in every case? For the latter case: Which system do we use for that? For example, what do we do if there are relevant files on several different levels of the file tree?
* I have the feeling that the distinction between coverage data and DiffCoverage data is not entirely clear in the data points on the files. I assume, for example, the missing lines only refer to the code added by the PR? Perhaps we could then make this a bit clearer or, for example, as before, show both the coverage of the whole file and coverage of the added lines.

**Comment by ewjoachim** [comment]
> Is coverage_comment/ in this case supposed to be understood as COVERAGE_PATH or do we want to combine files in one folder in every case? For the latter case: Which system do we use for that? For example, what do we do if there are relevant files on several different levels of the file tree?

What I had in mind was to iterate on all the files that appeared on the coverage report, group them by "full folder path" and then display all the files belonging in the same folder together. No nesting. So for example:

- `a/b/`
  - `c.py`
  - `d.py`
- `a/b/e/`
  - `f.py`
- `g/`
  - `h.py`

> I have the feeling that the distinction between coverage data and DiffCoverage data is not entirely clear in the data points on the files. I assume, for example, the missing lines only refer to the code added by the PR? Perhaps we could then make this a bit clearer or, for example, as before, show both the coverage of the whole file and coverage of the added lines.

Excellent point. I guess it would make sense to have the new coverage (or even the evolution in coverage) for each file, but also the diff coverage, and those are 2 different things.
Maybe instead of `Stmts | Miss | Cover | Missing`, we should have `Previous file coverage rate | Current file coverage rate | Coverage rate of added lines | Lines missing coverage | Added lines missing coverage`. (this would mean we'd need to store much more precise data in [the json file](https://github.com/py-cov-action/python-coverage-comment-action/blob/python-coverage-comment-action-data/data.json))
- "Lines missing coverage" will have to link to the branch and not the PR.
- "Added lines missing coverage" can link to the PR diff

Is it too much ? I'm afraid it might be overwhelming.

**Comment by ewjoachim** [comment]
If we have previous coverage

---

## Coverage report
Coverage for the whole project went from 100% to 99% 83% of the code lines added by this PR are covered

<details><summary>Coverage details</summary><table><thead>
<tr><th colspan="5">
<h3>Coverage Details</h3>
<em>This table shows all the files where coverage has changed</em>
</th></tr>
<tr><th>File</th><th>Previous coverage rate</th><th>Current coverage rate</th><th>Coverage rate of added lines</th><td align="center"><strong>Lines missing coverage</strong><br><em>(Lines added by this PR in bold)</em></td></tr>
</thead>
<tbody>
<tr><td colspan="5"><b>coverage_comment/</b></td></tr>
<tr>
<td>&nbsp;&nbsp;<a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-61bf637d10e8406acddf352767e17c4c775522b38e64c5f0e065750bcc1d8014">files.py</a></td>
<td align="center"><ruby>96%<rt>64/66</rt></ruby></td>
<td align="center"><sub>65/66</sub><br/>98% 📈</td>
<td align="center"><sub>2/3</sub><br/>66%</td>
<td>
  <span align="center">
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/files.py#L66">66</a>,
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-61bf637d10e8406acddf352767e17c4c775522b38e64c5f0e065750bcc1d8014R74"><strong>74</strong></a>
  </span>
  <details>
    <summary></summary>

https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/files.py#L66
https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/files.py#L74

  </details>
</td>
</tr>
<tr>
<td>&nbsp;&nbsp;<a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-aa416c9a98a0fd16ca04ed4a3606bf634663109cd1562c05467181ad9b0a8a08">main.py</a></td>
<td align="center"><sub>64/66</sub><br/>96%</td>
<td align="center"><sub>65/66</sub><br/>98% 📈</td>
<td align="center"><sub>2/3</sub><br/>66%</td>
<td>
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L65-L66">65–66</a>,
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L79">79</a>

  <details>
    <summary></summary>

https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L65-L66
https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L79

  </details>
</td>
</tr>
</tbody>
<tfoot>
  <tr><td><b>Project Total</b></td><td><b>1055</b></td><td><b>739</b></td><td><b>99%</b></td><td>&nbsp;</td></tr>
  <tr><td><b>Added by PR</b></td><td><b>12</b></td><td><b>10</b></td><td><b>83%</b></td><td>&nbsp;</td></tr>
</tfoot>
</table>

<sub>This report was generated by [python-coverage-comment-action](https://github.com/py-cov-action/python-coverage-comment-action)</sub>
</details>

---

If we don't have previous coverage

---

## Coverage report
Coverage for the whole project is 99% 83% of the code lines added by this PR are covered

<details><summary>Coverage details</summary><table><thead>
<tr><th colspan="4">
<h3>Coverage Details</h3>
<em>This table shows all the files where coverage has changed</em>
</th></tr>
<tr><th>File</th><th>Current coverage rate</th><th>Coverage rate of added lines</th><td align="center"><strong>Lines missing coverage</strong><br><em>(Lines added by this PR in bold)</em></td></tr>
</thead>
<tbody>
<tr><td colspan="4"><b>coverage_comment/</b></td></tr>
<tr>
<td>&nbsp;&nbsp;<a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-61bf637d10e8406acddf352767e17c4c775522b38e64c5f0e065750bcc1d8014">files.py</a></td>
<td align="center"><sub>65/66</sub><br/>98% 📈</td>
<td align="center"><sub>2/3</sub><br/>66%</td>
<td>
  <span align="center">
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/files.py#L66">66</a>,
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-61bf637d10e8406acddf352767e17c4c775522b38e64c5f0e065750bcc1d8014R74"><strong>74</strong></a>
  </span>
  <details>
    <summary></summary>

https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/files.py#L66
https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/files.py#L74

  </details>
</td>
</tr>
<tr>
<td>&nbsp;&nbsp;<a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-aa416c9a98a0fd16ca04ed4a3606bf634663109cd1562c05467181ad9b0a8a08">main.py</a></td>
<td align="center"><sub>65/66</sub><br/>98% 📈</td>
<td align="center"><sub>2/3</sub><br/>66%</td>
<td>
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L65-L66">65–66</a>,
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L79">79</a>

  <details>
    <summary></summary>

https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L65-L66
https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L79

  </details>
</td>
</tr>
</tbody>
<tfoot>
  <tr><td><b>Project Total</b></td><td><b>1055</b></td><td><b>739</b></td><td><b>99%</b></td><td>&nbsp;</td></tr>
  <tr><td><b>Added by PR</b></td><td><b>12</b></td><td><b>10</b></td><td><b>83%</b></td><td>&nbsp;</td></tr>
</tfoot>
</table>

[!NOTE]
No coverage data of the default branch was found for comparison. A possible reason for this is that the coverage action has not yet run after a push event and the data is therefore not yet initialized.

<sub>This report was generated by [python-coverage-comment-action](https://github.com/py-cov-action/python-coverage-comment-action)</sub>
</details>

**Comment by ewjoachim** [comment]
Note:

I don't know which of those is better:

<ruby>96%<rt>64/66</rt></ruby>

vs

<sub>65/66</sub><br/>98%

**Comment by kieferro** [comment]
> group them by "full folder path" and then display all the files belonging in the same folder together. No nesting.

Yes , sounds good.

**Comment by kieferro** [comment]
I also like the new proposal, but I found the old one a bit tidier and easier to understand at first glance and actually I don't think it needs that many changes to the structure. I would just add a delta for each value. In order to highlight this in colour, we would have to work with a relatively large number of badges, because Markdown unfortunately doesn't support this natively, but otherwise why not just modify the original idea a little bit (The numerical values don't make sense, but you get the idea):

<hr>


## Coverage report
Coverage for the whole project went from 100% to 99% 83% of the code lines added by this PR are covered Branch coverage for the whole project on this PR is 50%.

<details><summary>Coverage details</summary><table><thead>
  <tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Cover (new lines)</th><th>Missing</th></tr>
</thead>
<tbody>
<tr><td colspan="5"><b>coverage_comment/</b></td></tr>
<tr>
<td>&nbsp;&nbsp;<a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-61bf637d10e8406acddf352767e17c4c775522b38e64c5f0e065750bcc1d8014">files.py</a></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td>
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-61bf637d10e8406acddf352767e17c4c775522b38e64c5f0e065750bcc1d8014R74">74</a>
  <details>
    <summary></summary>

https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/files.py#L74

  </details>
</td>

<tr>
<td>&nbsp;&nbsp;<a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-aa416c9a98a0fd16ca04ed4a3606bf634663109cd1562c05467181ad9b0a8a08">main.py</a></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td>
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-aa416c9a98a0fd16ca04ed4a3606bf634663109cd1562c05467181ad9b0a8a08R65-R66">65–66</a>,
  <a href="https://github.com/py-cov-action/python-coverage-comment-action/pull/235/files#diff-aa416c9a98a0fd16ca04ed4a3606bf634663109cd1562c05467181ad9b0a8a08R79">79</a>

  <details>
    <summary></summary>

https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L65-L66
https://github.com/py-cov-action/python-coverage-comment-action/blob/4e3ee3a9d2131c2a1ad3e35ee7dbeee737a1f88f/coverage_comment/main.py#L79

  </details>
</td>
</tr>
</tbody>
<tfoot>
  <tr><td><b>Project Total</b></td><td align="center"></td><td  align="center"></td><td  align="center"></td><td align="center"></td><td>&nbsp;</td></tr>
</tfoot>
</table>

<sub>This report was generated by [python-coverage-comment-action](https://github.com/py-cov-action/python-coverage-comment-action)</sub>
</details>

<hr>

Also, I'm not quite sure if it makes sense to link all the missing lines. I can imagine that there are projects that do not yet have much coverage, which means that the missing lines that are actually relevant for PR are lost in the mass of missing lines. That's why I wonder if we shouldn't just focus on those?

**Comment by ewjoachim** [comment]
> Also, I'm not quite sure if it makes sense to link all the missing lines

Just to make it clear: not all the missing lines, just the ones inside files where coverage has changed for the PR. Reasoning is that sometimes, coverage changed somewhere because of a change elsewhere. For example, you want to move a test, and delete it but forget to re-add it elsewhere, the tested code lost coverage but it's not part of the diff, it's still linked to the PR.

I like the idea of badges, I note that GitHub adapts the badge size to the available size, making some quite small:
image
(Not saying it's a problem we need to solve. We can be ok leaving it as-is)

There's always a small ambiguity when saying `88% (+10%)` because it's not clear if 10% applies to 88% (so it was 80% before and we added 10% of 80% which is 8 percentage points leading to 88%) or to the underlying value (so it was 78% before). But it's not a big ambiguity, I think it can be ok it we choose to keep it.

In my example, I've removed the branch coverage rate because I'm not sure it's more useful than confusing. We're in the context of a PR, and "branch coverage" could be easily understood as a synonym for "PR coverage" though it's completely different.

We're not displaying the number of new line added/covered, is this by design ? We're only displaying the percentage.

I had added a header row to the table, do you think it's worth keeping ?

**Comment by kieferro** [comment]
> Not all the missing lines, just the ones inside files where coverage has changed for the PR. Reasoning is that sometimes, coverage changed somewhere because of a change elsewhere.

Good point, I hadn't thought about that but, of course, it makes a lot of sense to do it that way.

> There's always a small ambiguity when saying `88% (+10%)` because it's not clear if 10% applies to 88%

Yes, I have thought about that too. I also thought about whether it would make more sense to write `(-0.21pp)` (pp meaning percentage points), but I think that would lead to even more confusion. Maybe we can add a footnote or a little explanation.




> In my example, I've removed the branch coverage rate because I'm not sure it's more useful than confusing. We're in the context of a PR, and "branch coverage" could be easily understood as a synonym for "PR coverage" though it's completely different.

Ah sorry, I had just accidentally copied those from the original example. I'm completely on board with removing those :+1:



> We're not displaying the number of new line added/covered, is this by design ? We're only displaying the percentage.

I'm not quite sure what you mean. For example files.py had 64 statements before and now has two more so 66 and it had 2 not covered statements and now has 3 not covered statements. Are you referring to the difference between statements and lines or what other information would be necessary in your opinion?



> I had added a header row to the table, do you think it's worth keeping ?

I'm not sure, it takes up quite a lot of space. Why don't we move the information from it to the area that is clicked to expand:

<details><summary>Coverage details (Information about all the files where coverage has changed)</summary></details>

**Comment by ewjoachim** [comment]
> I'm not quite sure what you mean. For example files.py had 64 statements before and now has two more so 66 and it had 2 not covered statements and now has 3 not covered statements. Are you referring to the difference between statements and lines or what other information would be necessary in your opinion?

Say files.py had 64 statements and now has 66, and has 50% of added lines covered. Without more information, you'd probably think you added 2 lines, one of which was covered. But maybe you actually rewrote the whole file and covered 33 lines. I think the number of added lines may be important and is not deduced just by seeing how many lines there were before and there are now because you don't know how many were deleted.

The list of lines missing coverage may help get a sense of this but it's only showing missing lines.

**Comment by kieferro** [comment]
Ah okay, I see. I have edited my proposal and also added this information. I think that it also looks a bit more consistent now. Would you agree with the layout and styling then?

**Comment by ewjoachim** [comment]
I think we're good!

**Comment by ewjoachim** [comment]
I've changed a detail on the `<details><summary>`: 

image

**Comment by kieferro** [comment]
I am currently working on the PR and I feel that it would be useful to make the selection of files that appear in the table a little different than it is now.
For example, if you delete a test case for a file, then if we go by DiffCoverage as before, the coverage loss in that file would not be shown.
So I think we need a different condition. The best thing I  can think of would be to include all files where the number of statements, misses or both have changed. Because in all these files something has changed in the tested code or in its coverage. What do you think about that @ewjoachim?

**Comment by ewjoachim** [comment]
Yes, "listing all files where coverage has changed" was my current understanding of what we wanted to do so I guess we're aligned ?
(That said, maybe we should limit to, say, 50 or 100 files. Like: we'd show the 100 files with the biggest difference in coverage, ordered by name)

**Comment by ewjoachim** [comment]
## Coverage report


Coverage for the whole project went from 100% to 76.47% 69.23% of the statement lines added by this PR are covered<details><summary>Click to see where and how coverage changed</summary><table><thead>
  <tr><th>File</th><th>Statements</th><th>Missing</th><th>Coverage</th><th>Coverage<br>(new lines)</th><th>Lines missing</th></tr>
</thead>
<tbody><tr>
<td>&nbsp;&nbsp;<b><a href="https://github.com/org/repo/pull/12/files#diff-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"></b></a></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/org/repo/pull/12/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3">code.py</a></td>

<td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3">This PR adds 5 to the number of statements in codebase/code.py, taking it from 6 to 11. The number of new statements is at least 5 but it may be higher if other statements were simultaneously removed.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3">This PR adds 3 to the number of statements missing coverage in codebase/code.py, taking it from 1 to 4. This may be the result of adding untested statements and/or removing the tests that were covering existing statements. Also, it's possible that more non-covered statements were added, while other non-covered statements were removed elsewhere in the file.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3">This PR removes 19.69696969696969696969696969 percentage points from the coverage rate (number of statements covered by the tests / total number of statements) in codebase/code.py, taking it from 83.33% to 63.63%.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3">This PR adds 6 statements to codebase/code.py, 0.5 of which are covered, the coverage rate on the diff is 50%.</a></td><td><a href="https://github.com/org/repo/pull/12/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3R12-R14">12-14</a>, <a href="https://github.com/org/repo/pull/12/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3R22-R22">22</a></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/org/repo/pull/12/files#diff-30cad827f61772ec66bb9ef8887058e6d8443a2afedb331d800feaa60228a26e">other.py</a></td>

<td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-30cad827f61772ec66bb9ef8887058e6d8443a2afedb331d800feaa60228a26e">This PR removes 3 from the number of statements in codebase/other.py, taking it from 6 to 3. The number of deleted statements is at least 3 but it may be higher if other statements were simultaneously added.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-30cad827f61772ec66bb9ef8887058e6d8443a2afedb331d800feaa60228a26e">This PR doesn't change the number of statements missing coverage in codebase/other.py, which is 0. Either the modifications in the file were only to covered lines, or the same number of statements missing coverage was simultenousely added to and removed from the file.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-30cad827f61772ec66bb9ef8887058e6d8443a2afedb331d800feaa60228a26e">This PR doesn't change the coverage rate (number of statements covered by the tests / total number of statements) in codebase/other.py, which is 100%.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-30cad827f61772ec66bb9ef8887058e6d8443a2afedb331d800feaa60228a26e">This PR does not seem to add statements to codebase/other.py.</a></td><td></td></tbody>
<tfoot>
<tr>
<td><b>Project Total</b></td>

<td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1">This PR adds 11 to the number of statements in the whole project, taking it from 6 to 17. The number of new statements is at least 11 but it may be higher if other statements were simultaneously removed.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1">This PR adds 4 to the number of statements missing coverage in the whole project, taking it from 0 to 4. This may be the result of adding untested statements and/or removing the tests that were covering existing statements. Also, it's possible that more non-covered statements were added, while other non-covered statements were removed elsewhere in the file.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1">This PR removes 23.52941176470588235294117647 percentage points from the coverage rate (number of statements covered by the tests / total number of statements) in the whole project, taking it from 100% to 76.47%.</a></td><td align="center"><a href="https://github.com/org/repo/pull/12/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1">This PR adds 9 statements to the whole project, 0.6923076923076923076923076923 of which are covered, the coverage rate on the diff is 69.23%.</a></td><td>&nbsp;</td>
</tr>
</tfoot>
</table><sub>

This report was generated by [python-coverage-comment-action](https://github.com/py-cov-action/python-coverage-comment-action)</sub>
</details>

**Comment by ewjoachim** [comment]
Without previous
---

## Coverage report


 <details><summary>Click to see where and how coverage changed</summary><table><thead>
  <tr><th>File</th><th>Statements</th><th>Missing</th><th>Coverage</th><th>Coverage<br>(new stmts)</th><th>Lines missing</th></tr>
</thead>
<tbody><tr>
<td colspan="6">&nbsp;&nbsp;<b>codebase</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3">code.py</a></td>
<td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3"></a></td><td><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3R3-R3">3</a>, <a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3R7-R12">7-12</a></td></tbody>
<tfoot>
<tr>
<td><b>Project Total</b></td>
<td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td>&nbsp;</td>
</tr>
</tfoot>
</table><sub>
This report was generated by [python-coverage-comment-action](https://github.com/py-cov-action/python-coverage-comment-action)
</sub></details>

**Comment by ewjoachim** [comment]
## Coverage report


 <details><summary>Click to see where and how coverage changed</summary><table><thead>
  <tr><th>File</th><th>Statements</th><th>Missing</th><th>Coverage</th><th>Coverage<br>(new stmts)</th><th>Lines missing</th></tr>
</thead>
<tbody><tr>
<td colspan="6">&nbsp;&nbsp;<b>codebase</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3">code.py</a></td>
<td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3"></a></td><td><a href="https://github.com/org/repo/pull/3/files#diff-c05d5557f0c1ff3761df2f49e3b541cfc161f4f0d63e2a66d568f090065bc3d3R6-R8">6-8</a></td></tbody>
<tfoot>
<tr>
<td><b>Project Total</b></td>
<td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/org/repo/pull/3/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td>&nbsp;</td>
</tr>
</tfoot>
</table><sub>

This report was generated by [python-coverage-comment-action](https://github.com/py-cov-action/python-coverage-comment-action)

</sub></details>

**Comment by ewjoachim** [comment]
Closed by #211

**Pull request closed without merging**
