### PR TITLE
Windows-specific instructions

### LINKED ISSUE #162: Action can't find source code to report
I'm facing an error, followed the instruction, error says its permission but it doesn't matter the permission I set.
Here's the debug logs minus folder paths("redacted" is my main package), after this it jjust repeats the last few lines for every file in the project
https://pastebin.com/rcv95F7b

```
##.coveragerc
[run]

branch = True
dynamic_context = test_function
source = redacted
relative_files = True

[report]
precision = 2
sort = Miss
show_missing = True
ignore_errors = True

[html]
show_contexts = True
```
the generation works locally

### PR DESCRIPTION
**Pull request by ewjoachim**
(Original PR: https://github.com/ArthurNRL/python-coverage-comment-action/pull/1 by @ArthurNRL )

Closes #162

### CODE REVIEW

**Review by kieferro — APPROVED** [review]
:+1: Looks good. Is there any reason why the e2e tests didn't run?

**Comment by ewjoachim** [comment]
```tests/end_to_end/test_all.py::test_public_repo SKIPPED (requires COVERAGE_COMMENT_E2E_GITHUB_TOKEN_USER_1 in environment variables) [ 99%]
tests/end_to_end/test_all.py::test_private_repo SKIPPED (requires COVERAGE_COMMENT_E2E_GITHUB_TOKEN_USER_1 in environment variables) [100%]```

Wow how did you even had the idea to check that ?

**Comment by ewjoachim** [comment]
Because the original branch in in a fork. I guess if we ran the e2e tests, then anyone would easily be able to steal our tokens.

**Comment by kieferro** [comment]
> Wow how did you even had the idea to check that ?

The tests were way too fast 😄

**Comment by ewjoachim** [comment]
Thank you @ArthurNRL and congratulations for you first PR in the repo :) Thank you and see you around.

**Pull request merged**
